version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud-productos"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1em0nds8j43xl"
s3_prefix = "crud-productos"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
